export const CHANGE_CLIENT_ENV = 'CHANGE_CLIENT_ENV';
export const CHANGE_CLIENT_ENV_SUCCESS = 'CHANGE_CLIENT_ENV_SUCCESS';
export const CHANGE_CLIENT_REFERER = 'CHANGE_CLIENT_REFERER';
export const CHANGE_CLIENT_REFERER_SUCCESS = 'CHANGE_CLIENT_REFERER_SUCCESS';
