export const FETCH_VIDEO_DATA = 'FETCH_VIDEO_DATA';
export const FETCH_VIDEO_DATA_SUCCESS = 'FETCH_VIDEO_DATA_SUCCESS';
export const FETCH_VIDEO_DATA_FAILED = 'FETCH_VIDEO_DATA_FAILED';

export const CLEAR_FETCH_VIDEO_DATA_ERROR_MESSAGE =
  'CLEAR_FETCH_VIDEO_DATA_ERROR_MESSAGE';
export const CLEAR_VIDEO_DATA = 'CLEAR_VIDEO_DATA';
