export const FETCH_HOME_PAGE_DATA = 'FETCH_HOME_PAGE_DATA';
export const FETCH_HOME_PAGE_DATA_SUCCESS = 'FETCH_HOME_PAGE_DATA_SUCCESS';
export const FETCH_HOME_PAGE_DATA_FAILED = 'FETCH_HOME_PAGE_DATA_FAILED';
export const SET_NEED_UPDATE_HOME_PAGE_DATA = 'SET_NEED_UPDATE_HOME_PAGE_DATA';
