export const FETCH_FYC_USER = 'FETCH_FYC_USER';
export const FETCH_PRESS_USER = 'FETCH_PRESS_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const CLEAR_FETCH_FYC_USER_ERROR_MESSAGE =
  'CLEAR_FETCH_FYC_USER_ERROR_MESSAGE';
