export const FETCH_SHOW_DATA = 'FETCH_SHOW_DATA';
export const FETCH_SHOW_DATA_SUCCESS = 'FETCH_SHOW_DATA_SUCCESS';
export const FETCH_SHOW_DATA_FAILED = 'FETCH_SHOW_DATA_FAILED';

export const FETCH_SHOW_EPISODES_DATA_SUCCESS =
  'FETCH_SHOW_EPISODES_DATA_SUCCESS';
export const FETCH_SHOW_EPISODES_DATA_FAILED =
  'FETCH_SHOW_EPISODES_DATA_FAILED';
