export const FETCH_SHOW_DATA = 'FETCH_SHOW_DATA';
export const FETCH_SHOW_DATA_SUCCESS = 'FETCH_SHOW_DATA_SUCCESS';
export const FETCH_SHOW_DATA_FAILED = 'FETCH_SHOW_DATA_FAILED';
export const CLEAR_SHOW_DATA = 'CLEAR_SHOW_DATA';

export const FETCH_SHOW_EPISODES_DATA_SUCCESS =
'FETCH_SHOW_EPISODES_DATA_SUCCESS';
export const FETCH_SHOW_EPISODES_DATA_FAILED =
'FETCH_SHOW_EPISODES_DATA_FAILED';
export const CLEAR_SHOW_EPISODES = 'CLEAR_SHOW_EPISODES';
export const SET_SELECTED_EPISODE = 'SET_SELECTED_EPISODE';
export const CLEAR_SELECTED_EPISODE = 'CLEAR_SELECTED_EPISODE';

export const SET_SHOW_BANNER = 'SET_SHOW_BANNER';
export const CLEAR_SHOW_BANNER = 'CLEAR_SHOW_BANNER';
